### ISSUE TITLE
Bundler project Fusion and renaming?

### ISSUE THREAD

**Issue by benoit-pereira-da-silva** [Bartlebys/Distribution#1]
There is a famous Ruby Dependency manager is named [Bundler] (http://bundler.io)

I do propose : 

- to name this component  Bartleby's-Disrtribution-Manager BDM
- And to relocate all the files into ```github.com/Bartlebys/Distribution/Distribution-Manager.```
- The travis integration should  be updated.

May be a more simple approach  can be:
1.  to delete ```github.com/Bartlebys/Bartlebys/Distribution```
2.  rename *Bundler* to *Distribution*
3. merge the ReadMe.

**Comment by MartinDelille** [comment]
The README.md merge is done here: 3fa2ff4 but links are not valid: https://github.com/Bartlebys/Bundler/blob/master/README.md#the-distribution-includes
